```{r,results="asis",echo=FALSE}
opts_chunk$set(warnings = FALSE)

# LOAD DETAILS
details <- fromJSON(paste(readLines("details.JSON"), collapse=""))

# FUNCTIONS FOR FORMATTING TABLES
pandify <- function(data.table){
	pandoc.table.return(data.table, styl="multiline", split.tables= 200, split.cells = 50, justify = "left")
}

print_Line <- function(name, value) writeLines(paste0("**",name,"**: ", value, "\n"))

print_header <- function(name, hash="##") writeLines(paste(hash, name,"\n"))

print_lines <- function(x){
	for(l in names(x))
		print_Line(l, x[[l]])
}

print_lines_with_header <-function(x, hash="###"){
	for(n in names(x)){
		print_header(n, hash)
		print_lines(x[[n]])
	}
}

print_lines_with_header_simple <-function(x, hash="###"){
	for(n in names(x)){
		print_header(n, hash)
		writeLines(paste0(x[[n]], "\n"))
	}
}

print_header(paste("Data from \"",  details$publication$title, "\""), hash="#")
```
## Publication

```{r,results="asis",echo=FALSE}
print_lines(details$publication[c('citation', 'doi', 'abstract')])
```
## Rights

```{r,results="asis",echo=FALSE}
writeLines(paste(details$rights, "\n"))
```

## Creator
```{r,results="asis",echo=FALSE}
print_lines_with_header(details$creator)
```

```{r,results="asis",echo=FALSE}
if(!is.null(details$associatedParty)){
	print_header("Contributors", "##")
	print_lines_with_header(details$associatedParty)
}
```

## Methods

```{r,results="asis",echo=FALSE}
print_lines_with_header_simple(details$methods)
```

## File descriptions

Below is a list of the various files provided for this dataset, and the variables within each.

```{r,results="asis",echo=FALSE}

for(n in names(details$files)){
	data <- details$files[[n]]
	writeLines("\\newpage \n")
	print_header(basename(data$path), "###")
	print_Line("contents", data$description)
	print_Line("metadata", basename(data$metadata))
	mytext <- pandify(read.csv(data$metadata, stringsAsFactors=FALSE))
	writeLines(mytext)
}
```
